header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'licenses'
    - 'LICENSE'
    - 'NOTICE'
    - '.git*'
    - '**/*.md'
    - '.github/**'
    - '.licenserc.yaml'
    - '.mvn/**'
    - 'LICENSE-binary'
    - 'NOTICE-binary'
    - 'checkstyle.xml'
    - '**/.gitignore'
    - 'example/mqtt-customize/src/main/resources/META-INF/services/org.apache.iotdb.db.org.apache.iotdb.db.protocol.mqtt.PayloadFormatter'
    - 'grafana-plugin/package.json'
    - 'grafana-plugin/src/plugin.json'
    - 'grafana-plugin/tsconfig.json'
    - 'grafana-plugin/yarn.lock'
    - 'site/src/main/.vuepress/redirects'
    - 'site/src/main/package.json'
    - 'zeppelin-interpreter/IoTDB-Zeppelin-Demo.zpln'
    - 'zeppelin-interpreter/src/main/resources/interpreter-setting.json'

  comment: on-failure